#! /bin/sh -e

# postrm - finish removal of the 'console-tools'-package


# FIXME try getting this inserted by debhelper
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
fi

if [ "$1" = purge ]; then
    rm -f /etc/console-tools/config
fi
		
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d console-screen.sh remove >/dev/null || exit $?
fi
# End automatically added section

