#!/bin/sh -e

if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
    invoke-rc.d xinetd stop
elif [ -x /etc/init.d/xinetd ]; then
    /etc/init.d/xinetd stop
fi

if [ "$1" = "remove" ]; then
    echo "Note: all inetd services have been terminated."
fi

# Automatically added by dh_installinit
if [ -e "/etc/init/xinetd.conf" ] && [ "$1" = remove ]; then
	# stop fails if not running
	stop xinetd || :
fi
# End automatically added section

